# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i_Bs79iO5jzp8fCZILzBP1dalYMn-8TT
"""

nilai1 = 10
nilai2 = 20
nilai3 = 100

total = nilai1 + nilai2 + nilai3
print(total)