# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i_Bs79iO5jzp8fCZILzBP1dalYMn-8TT
"""

counter = 100
jarak = 104.5
name = "nina"

a = b = c = 200
name, city, salary = "Sabine", 'Surabaya', 70000

print(counter)
print(jarak)
print(name)
print(a, b, c)
print(city)