# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i_Bs79iO5jzp8fCZILzBP1dalYMn-8TT
"""

myStr = 'Hello, Surabaya'
print(len(myStr))

pegawai = 'Sabine'
print("nama : ", pegawai)
print("pass" + "word")

#age = 35
#myText = 'Age is'
#print(mytext + age) #Error

age = 35
myText = 'Age is '
print(myText + str(age))

print("Python " * 3)