# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i_Bs79iO5jzp8fCZILzBP1dalYMn-8TT
"""

print(True or False) #output : True

print(True and False) #output : False

print(100>200) #output : False

a=9
print(a>0) #output : True

b=10
print(a>b) #output : False