# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i_Bs79iO5jzp8fCZILzBP1dalYMn-8TT
"""

a=10; b=20
mylist=[1,2,3,4,5];

a=2
if(a in mylist):
  print("Line 3 a is available in the given list")
else:
  print("Line 3 a is not available in the given list")