# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i_Bs79iO5jzp8fCZILzBP1dalYMn-8TT
"""

cabang = ['Jakarta','Bogor','Bandung','Solo','Malang','Surabaya','Banyuwangi','Denpasar','Makassar']
print (cabang)