# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i_Bs79iO5jzp8fCZILzBP1dalYMn-8TT
"""

print(str(3.14))
print(int("2345"))
print(int(75.99999))
print(float("5.678"))
print(float(9))