# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i_Bs79iO5jzp8fCZILzBP1dalYMn-8TT
"""

s = "SaMurai"
s.lower()
print(s)

s2=s.lower()
print(s2)

name = input('What is your name? ')

print('Hi ' + name +'!')