# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i_Bs79iO5jzp8fCZILzBP1dalYMn-8TT
"""

nama='Sabine'

kalimat = 'This is a sentence.'

Paragraf = """This is a paragraph.
Paragraph are made up of a several lines and sentences."""

print(nama)
print(kalimat)
print(Paragraf)

print(nama[0:5])
print(nama[2:])
print(kalimat[-8:-1])